### ISSUE TITLE
Round / Truncate some values. A and V to 9 decimal places can't be that accurate

### ISSUE THREAD

**Issue by Chewie9999** [dodo5522/tsmppt60_driver#8]
Great program, and thank you - this has saved me a lot of work!
Can I suggest for some of the values you round them to 2 decimal places, as in the Web GUI, eg. battery voltage and Amps:

```
 if scale_factor == "V":
            return round( raw_value * self._vscale / pow(2, 15), 2)
        elif scale_factor == "A":
            return round( raw_value * self._iscale / pow(2, 15), 2)
```
I doubt the MorningStar controller is accurate enough to go to this level of detail, and must just be a rounding error on the scaling process.

**Comment by dodo5522** [comment]
@Chewie9999 Thanks a lot for your request. I agree with you and will round the values.
