### ISSUE TITLE
Feature Request: Add Controller Status To output

### ISSUE THREAD

**Issue by Chewie9999** [dodo5522/tsmppt60_driver#9]
I tried to implement this myself, but don't know enough Python to figure out what to do :disappointed: 

State can be one of the following:

- 0 : Start,
- 1 : "Night Check",
- 2 : Disconnect,
- 3 : Night,
- 4 : Fault,
- 5 : MPPT,
- 6 : Absorption,
- 7 : Float,
- 8 : Equalize

from modbus register 0x0032 (50 & UINT16).
I tried to create a "scale_factor" using a dict and created a new class, but failed badly :cry: , maybe because all the values are expected to be numeric, not text? :shrug: I'm sorry I can't just send you the code....

**Comment by dodo5522** [comment]
@Chewie9999 Your request is nice feature! I also want it.

I've implemented new class `OperatingConditions` to get the charge state (0x0032) and led state (0x0031) on this PR https://github.com/dodo5522/tsmppt60_driver/pull/10. I tested the code can get charge state `3` as `NIGHT`. I want to continue testing more and organize code, then merge and release.

**Comment by Chewie9999** [comment]
That's great! I've just tested it myself, and both Charge State and LED Status are showing the correct values
